version: '3.3'

services:

  db:
    build: db
    image: patrickmslatteryvt/k8s-wordsmith-db:dk

  words:
    build: words
    image: patrickmslatteryvt/k8s-wordsmith-api:dk
    deploy:
      replicas: 5

  web:
    build: web
    image: patrickmslatteryvt/k8s-wordsmith-web:dk
    ports:
     - "8080:80"
